### ISSUE TITLE
Model Prediction Problem

### ISSUE THREAD

**Issue by impulsecorp** [radi-cho/GatedTabTransformer-Applications#1]
I am trying GatedTabTransformer on the Titanic dataset and it works fine, but I don't understand how to use the trained model to make predictions.  Your page at https://github.com/radi-cho/GatedTabTransformer shows to do it like this:
pred = model(x_categ, x_cont)

I have a validation dataset and I divided it into categorical and continuous like you do in the training set:
--------------------
val_cat = df_cheat[['Pclass', 'Sex', 'SibSp', 'Parch', 'Cabin', 'Embarked']] #, axis=1)
val_cont = df_cheat[['Age', 'Fare']] #, axis=1)
--------------------
and when I output it, it looks fine. Then I try any of these:
preds = model(val_cat, val_cont)
preds = model(val_cat, Tensor(val_cont.values))
preds = model(val_cat, val_cont.values)
it gives me this error:
TypeError: '(slice(None, None, None), 0)' is an invalid key

**Comment by radi-cho** [comment]
Can you please share the code snippet for training which works and the code of how you create the validation set?

**Comment by impulsecorp** [comment]
The validation set for Titanic is a "cheat" version of the Kaggle prediction set with 100% accuracy. 
I am running it in Google Colab, so I saved it to a .py file instead and the code is below (it automatically downloads the data remotely from my server):

!git clone https://github.com/radi-cho/GatedTabTransformer
!pip install fastcore
!pip install -U fastai
!pip install tsai

import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport
import pandas_profiling as pdp
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from fastcore.test import test_eq
from fastcore.basics import first
from fastai.data.external import untar_data, URLs
from fastai.tabular.data import TabularDataLoaders
from fastai.tabular.core import Categorify, FillMissing
from fastai.data.transforms import Normalize

from tsai.all import *
from tsai.models.GatedTabTransformer import GatedTabTransformer

import warnings
warnings.filterwarnings('ignore')

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

df = pd.read_csv("https://boredhumans.com/datasets/titanic_ac.csv")

#df = df.astype(str)

dls = TabularDataLoaders.from_df(df, path='.', y_names='Survived',
    cat_names = ['Pclass', 'Sex', 'SibSp', 'Parch', 'Cabin', 'Embarked'],
    cont_names = ['Age', 'Fare'],
    procs = [Categorify, FillMissing, Normalize])

def MSELossFlatBatch(bs, *args, **kwargs):
    loss = MSELossFlat()
    return lambda inp, targ: loss(inp, targ) / bs

model = GatedTabTransformer(dls.classes, dls.cont_names, dls.c)
learn = Learner(dls, model, cbs=ShowGraph(), loss_func=MSELossFlatBatch(dls.bs))
#learn.fit_one_cycle(80, 1e-3)
learn.fit_one_cycle(3, 1e-3)

df_cheat = pd.read_csv("https://boredhumans.com/datasets/titanic_ac_test.csv")

val_data = df_cheat.drop(['Survived'], axis=1)
val_target = df_cheat['Survived']
val_data.shape, val_target.shape

val_cat = df_cheat[['Pclass', 'Sex', 'SibSp', 'Parch', 'Cabin', 'Embarked']] #, axis=1)
val_cont = df_cheat[['Age', 'Fare']] #, axis=1)

val_cont

preds = model(val_cat, Tensor(val_cont.values))
preds

accuracy_score(val_target, preds)
print(accuracy_score)

**Comment by impulsecorp** [comment]
You can email me at eric@impulsecorp.com if you want me to send you the notebook. Github doesn't allow me to post it here.

**Comment by radi-cho** [comment]
You can create a categorify method for your new data like so:
```python
from fastai.data.all import *
from fastai.tabular.all import *
from fastai.tabular.core import _apply_cats, _decode_cats 
```
```python
class CustomCategorify(TabularProc):
    "Transform the categorical variables to something similar to `pd.Categorical`"
    order = 1
    def __init__(self, classes=None):
        if classes is None: classes = defaultdict(L)
        store_attr()
        super().__init__()
    def setups(self, to):
        for n in to.cat_names:
            if n not in self.classes or is_categorical_dtype(to[n]):
                self.classes[n] = CategoryMap(to.iloc[:,n].items, add_na=n)

    def encodes(self, to): to.transform(to.cat_names, partial(_apply_cats, self.classes, 1))
    def decodes(self, to): to.transform(to.cat_names, partial(_decode_cats, self.classes))
    def __getitem__(self,k): return self.classes[k]
```

And you can create a new data loader for your validation data as follows:
```python
data = pd.DataFrame(YOUR_DATA, index=[0], dtype=np.float32) # In your case this is called df_cheat
custom_categorify = CustomCategorify(classes=dls.classes) # The classes from your original training data loader

predict_bs = 1
predict_loader = TabularDataLoaders.from_df(
    data,
    y_names = None,
    cat_names = cat_names,
    cont_names = cont_names,
    procs = [custom_categorify],
    bs = predict_bs,
    shuffle = False,
    valid_idx = ()
)
```

Which you can then use like a normal loader. You can iterate it if it contains multiple samples. In my example I retrieve only the first sample:
```python
x_cat, x_cont, _ = next(iter(predict_loader.train))
result = model(x_cat, x_cont)
```

**Comment by radi-cho** [comment]
@impulsecorp I am sorry I pasted too much code initially. The example is now clean.

**Comment by impulsecorp** [comment]
Thanks, I will try that and let you know if it works.

**Comment by impulsecorp** [comment]
I am confused about this part:  predict_bs = 1
I need to have the model make predictions for all 418 records in hold-out dataset (df_cheat).
I then need to get an accuracy score, something like:
accuracy_score(val_target, preds)
print(accuracy_score)

**Comment by radi-cho** [comment]
You can iterate through the new dataset and evaluate the samples at each step.

**Comment by radi-cho** [comment]
Please reopen if there are any issues.
